name: kdef
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Install kdef
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: peter-evans/kdef
          tag: v0.4.0

      - name: Toggle dry-run
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "push" ]] && [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "dry-run=" >> $GITHUB_OUTPUT;
          else
              echo "dry-run=--dry-run" >> $GITHUB_OUTPUT;
          fi

      - uses: actions/checkout@v3

      - name: Apply definitions
        run: |
          kdef \
            -X sasl.user=${{ secrets.SASL_USER }} \
            -X sasl.pass=${{ secrets.SASL_PASS }} \
            apply defs/**/*.yml \
              ${{ steps.vars.outputs.dry-run }} \
              --continue-on-error
