project_name: kdef

before:
  hooks:
    - go mod tidy

snapshot:
  name_template: "{{ incpatch .Version }}-next"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  filters:
    exclude:
      - Merge branch

release:
  draft: true

brews:
  - tap:
      owner: peter-evans
      name: homebrew-kdef
    folder: Formula
    commit_author:
      name: Peter Evans
      email: mail@peterevans.dev
    homepage: https://github.com/peter-evans/kdef
    description: Declarative resource management for Kafka
    license: MIT
    install: |-
      bin.install "kdef"
    test: |
      system "#{bin}/kdef --version"
    skip_upload: false

dockers:
  - image_templates:
      - "peterevans/kdef:latest" # TODO: make repo public
      - "peterevans/kdef:{{ .Version }}"
      - "ghcr.io/peter-evans/kdef:latest"
      - "ghcr.io/peter-evans/kdef:{{ .Version }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--platform=linux/amd64"
    skip_push: false
