project_name: kdef

before:
  hooks:
    - go mod tidy

snapshot:
  name_template: "{{ incpatch .Version }}-next"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      # - docs/* # TODO

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  filters:
    exclude:
      - Merge branch

release:
  draft: true

brews:
  - tap:
      owner: peter-evans
      name: homebrew-kdef
    folder: Formula
    commit_author:
      name: Peter Evans
      email: mail@peterevans.dev
    homepage:  https://github.com/peter-evans/kdef
    description: Declarative resource management for Kafka
    license: MIT
    install: |-
      bin.install "kdef"
    test: |
      system "#{bin}/kdef --version"
    skip_upload: false
