apiVersion: v1
kind: topic
metadata:
  name: store.events.order-updated
  labels:
    producer: storefront
spec:
  configs:
    retention.ms: "86400000"
  partitions: 6
  replicationFactor: 2
  assignments:
    - [1, 2]
    - [2, 3]
    - [3, 1]
    - [1, 2]
    - [2, 3]
    - [3, 1]
