apiVersion: v1
kind: topic
metadata:
  name: store.events.order-picked
spec:
  configs:
    retention.ms: "86400000"
  partitions: 4
  replicationFactor: 2
  rackAssignments:
    - ["zone-a", "zone-b"]
    - ["zone-b", "zone-c"]
    - ["zone-c", "zone-a"]
    - ["zone-a", "zone-b"]
