site_name: kdef
site_description: Declarative resource management for Kafka
site_author: Peter Evans
site_url: https://peter-evans.github.io/kdef
copyright: Copyright &copy; 2021 Peter Evans
repo_name: peter-evans/kdef
repo_url: https://github.com/peter-evans/kdef
edit_uri: edit/main/docs/docs/

theme:
  name: material
  language: en
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/peter-evans
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/peterevans0
